apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: service-api-app
spec:
  selector:
    matchLabels:
      app: service-api-app
  replicas: 20
  template:
    metadata:
      labels:
        app: service-api-app
    spec:
      containers:
      - name: node-api-postgres
        image: "<your-container-image-url>"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        env:
          - name:  "AZURE_SERVICEBUS_CONNECTION_STRING"
            value: ""
          - name: "AZURE_SERVICEBUS_QUEUE_NAME"
            value: ""
          - name: "AZURE_SERVICEBUS_TOPIC_NAME"
            value: ""
          - name: "POSTGRES_CONNECTION_STRING"
            value: ""